# Site settings
title: T.J. Telan
email: tj@tjtelan.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tjtelan.github.io" # the base hostname & protocol for your site
twitter_username: ellkae
github_username:  tjtelan

permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/:num"

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, test_local.sh]

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

sass:
  sass_dir: _sass

google_analytics: UA-21509172-1

gems:
#- jekyll-mentions
#- jemoji
#- jekyll-redirect-from
#- jekyll-sitemap
#- jekyll-feed
- jekyll-paginate
