title = "T.J. Telan"
description = "Somewhere between hardware and software"
# The URL the site will be built for
base_url = "https://tjtelan.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"

generate_feed = true
feed_filename = "atom.xml"
rss_limit = 20
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", feed = true},
]

[extra]
# Put all your custom variables here
hyde_links = [
  {url = "/now/", name = "Now"},
  {url = "https://github.com/tjtelan", name = "Github"},
  {url = "/about/", name = "About"},
  {url = "/atom.xml", name = "RSS"},
]
ignored_content = ["*.sh","*.py","Pipenv*","Dockerfile","docker-compose.yml",".*.swp", "content/blog/*.tmpl"]

#google_analytics_id = "UA-21509172-1"
google_analytics_id = "testtest123"

production_mode = false 
