version: '3'
services:
  zola:
    build: .
    image: tjtelan/zola
    ports:
      - 1111:1111
    volumes:
      - .:/blog
    # FIXME: this switch could maybe be less tedious
    #command: ["zola", "--config", "config.dev.toml", "serve", "--interface", "0.0.0.0" ]
    #command: ["zola", "--config", "config.toml", "serve", "--interface", "0.0.0.0" ]
