title = "T.J. Telan"
description = "[insert describing words here]"
# The URL the site will be built for
base_url = "https://tjtelan.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"

[extra]
# Put all your custom variables here
hyde_links = [
  {url = "/blog/", name = "Blog"},
  {url = "/now/", name = "Now"},
  {url = "https://github.com/tjtelan", name = "Github"},
]

generate_tags_pages = true
generate_categories_pages = true
rss_limit = 20

ignored_content = ["*.sh"]
